---
language: python
services: docker

env:
  global:
    - ROLE_OWNER: it-praktyk
    - ROLE_NAME: jenkins

  matrix:
    - scenario: default
      playbook: playbook.yml
    - scenario: debian-stable
      playbook: playbook-http-port.yml
    - scenario: debian-stable
      playbook: playbook-prefix.yml
    - scenario: centos-latest
      playbook: playbook-jenkins-version.yml
    - scenario: ubuntu-latest
      playbook: playbook-jenkins-version.yml
    - scenario: debian-stable
      playbook: playbook-plugins-with-home.yml

cache:
  - pip

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - ln -s ansible-role-$ROLE_NAME $ROLE_OWNER.$ROLE_NAME
  - cd $ROLE_OWNER.$ROLE_NAME

script:
  # Run tests.
  - playbook=${playbook} molecule test --scenario-name ${scenario:-default}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
