---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_version: "1.644"
    jenkins_release_line: "weekly"

  roles:
    - it-praktyk.jenkins

  post_tasks:
    - name: Verify installation of specific version of Jenkins - Red Hat
      block:
        - name: Check installed version of Jenkins
          command: rpm -q jenkins
          args:
            warn: false
          changed_when: false
          register: installed_jenkins_version

        - name: Print installed Jenkins package information.
          debug:
            var: installed_jenkins_version

        - name: Fail if version doesn't match what we wanted.
          fail:
          when: jenkins_version not in installed_jenkins_version.stdout
      when: ansible_os_family == 'RedHat'

    - name: Verify installation of specific version of Jenkins - Debian
      block:
        - name: Check installed version of Jenkins
          command: dpkg-query --list jenkins
          args:
            warn: false
          changed_when: false
          register: installed_jenkins_version

        - name: Print installed Jenkins package information.
          debug:
            var: installed_jenkins_version

        - name: Fail if version doesn't match what we wanted.
          fail:
          when: jenkins_version not in installed_jenkins_version.stdout
      when: ansible_os_family == 'Debian'
