---
- name: Default
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: Get java exucutable from the PATH
    shell: command -v java | wc -l
    changed_when: false
    register: java_count

  - name: Ensure that java is available
    assert:
      that:
        - java_count.stdout | int == 1

  - name: test the role
    include_role:
      name: ansible-role-jenkins
