---
- name: Converge
  hosts: all
  become: true

  vars:
    jenkins_url_prefix: /jenkins

  pre_tasks:
    - include_role:
        name: robertdebock.bootstrap
    - include_role:
        name: robertdebock.java
      vars:
        java_version: 8

  roles:
    - it-praktyk.jenkins

  post_tasks:
    - name: Ensure Jenkins is running with the specified prefix.
      uri:
        url: "http://127.0.0.1:8080{{ jenkins_url_prefix }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
