---
- name: Default
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
      vars:
        java_version: "{{ lookup('env', 'java_version')|default('11', true) }}"
