---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
lint:
  name: yamllint
driver:
  name: ${driver:-docker}
platforms:
  - name: centos-latest
    image: centos:latest
    pre_build_image: yes
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8980:8080/tcp
    volumes:
      - ${MOLECULE_SCENARIO_DIRECTORY:-.}:/tmp/packages:ro
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/${playbook:-playbook.yml}
    idempotence: ../resources/${playbook:-playbook.yml}
  lint:
    name: ansible-lint
scenario:
  name: centos-latest-volumes
  converge_sequence:
    - dependency
    - lint
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
