---
dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
lint:
  name: yamllint
driver:
  name: ${driver:-docker}
platforms:
  - name: ubuntu-latest
    image: ubuntu:latest
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/${playbook:-playbook.yml}
    idempotence: ../resources/${playbook:-playbook.yml}
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-latest
  converge_sequence:
    - dependency
    - lint
    - create
    - prepare
    - converge
  destroy_sequence:
    - cleanup
    - destroy
